-- V10__schema_fixes.sql
-- Fixing some errors of the db scheme

ALTER TABLE VENUE
    DROP COLUMN address;
ALTER TABLE VENUE
    ADD COLUMN street VARCHAR(255);
ALTER TABLE VENUE
    ADD COLUMN street_number VARCHAR(50);
ALTER TABLE VENUE
    ADD COLUMN city VARCHAR(100);
ALTER TABLE VENUE
    ADD COLUMN postal_code VARCHAR(20);
ALTER TABLE VENUE
    ADD COLUMN country VARCHAR(100);
ALTER TABLE VENUE
    ADD COLUMN additional_nfo TEXT;
ALTER TABLE BOOKING
    ADD COLUMN total_price NUMERIC(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE TICKET
    RENAME COLUMN birthday TO starts_at;
ALTER TABLE TICKET
    ALTER COLUMN starts_at TYPE TIMESTAMP;