@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0

skinparam DefaultFontName "Helvetica"
skinparam DefaultFontSize 12
skinparam class {
    BackgroundColor White
    BorderColor #333333
    ArrowColor #555555
}
skinparam nodesep 100
skinparam ranksep 100

skinparam ArrowThickness 1.2
skinparam ArrowFontStyle bold
skinparam ArrowFontSize 11
skinparam ArrowColor #444444


package "domain.venue" {
    class Venue <<Entity - Immutable>> {
        - id: Long
        - name: String
        - address: Address
        - additionalInfo: String
        --
        + Venue(id: Long, name: String, address: Address, ...)
    }

    class Address <<ValueObject - Immutable>> {
        - street: String
        - city: String
        - zipCode: String
        - country: String
        --
        + Address(street: String, city: String, ...)
    }
}

package "domain.resource" {
    abstract class Resource <<Abstract - Immutable>> {
        - id: Long
        - name: String
        - description: String
        --
        # Resource(id: Long, name: String, ...)
    }

    class Space {
        - capacity: int
    }

    class Equipment {
        - baseQuantity: int
    }

    class Service {
        - cost: BigDecimal
    }
}

Venue "1 " *-- "1 " Address : " posizionata a"
Venue "1    " o-right- " 0..*" Resource : "dispone di"
Resource <|-- Space
Resource <|-- Equipment
Resource <|-- Service
@endum